cc_library(
    name = "hashtable",
    srcs = [
        "hash.h",
        "hashtable.h",
    ],
    visibility = ["//test:__pkg__"],
)

cc_library(
    name = "slice",
    srcs = ["slice.h"],
    visibility = ["//test:__pkg__"],
)
